config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, skip: [:registrations, :passwords], controllers: {
        sessions: "admin/sessions",
      }
  devise_for :stores, skip: [:passwords], controllers: {
      registrations: "store/registrations",
      sessions: "store/sessions"
    }
  devise_for :customers, skip: [:passwords], controllers: {
      registrations: "public/registrations",
      sessions: "public/sessions"
    }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # guest login
  devise_scope :customer do
    post "customers/guest_sign_in", to: "public/sessions#guest_sign_in"
  end
  # 店舗側
  namespace :store do
    resources :stores do
      resources :items
    end
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
    resources :customers, only: [:index, :show, :edit, :update]
    get "search" => "searches#search"
    resources :item_categories, except: [:new, :show, :destroy]
    get 'item_categories/search'
  end
  # 管理者側
  namespace :admin do
    resources :stores, only: [:index, :show, :create]
    get '/', to: 'admin/home#top'
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:index, :show, :update]
    get "search" => "searches#search"
    resources :store_categories, except: [:new, :show, :destroy]
  end
  # 顧客側
  scope module: :public do
    resources :stores, only: [:index] do
      resources :store_categories, only: [:index, :show]
      resource :favorite, only: [:create, :destroy]
      resources :items, only: [:index, :show] do
        resources :item_categories, only: [:show]
      end
    end
    resources :customers, only: [:update] do
      member do
        get :favorites
      end
    end
      get '/customers/withdraw_confirm' => 'customers#withdraw_confirm', as: "withdraw_confirm"
      patch '/customers/withdraw' => 'customers#withdraw'
      get '/customers/mypage' => 'customers#show', as: "mypage"
      get '/customers/confirmation' => 'customers#confirmation', as: 'confirmation'
      get 'customers/infomation/edit' => 'customers#edit', as: "infomation"
    resources :cart_items, except: [:show, :edit, :new]
      delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
    get 'orders/thanks' => 'orders#thanks'
    post 'orders/confirm' => 'orders#confirm', as: "confirm"
    get 'orders/possible' => 'orders#possible', as: "possible"
    get 'orders/production' => 'orders#production', as: "prodction"
    get 'orders/review' => 'orders#review', as: "review"
    resources :orders, except: [:edit, :update, :destroy]
    root to: 'homes#top'
    get "search" => "searches#search"
  end
end

app/models/store_category.rb
class StoreCategory < ApplicationRecord
  has_many :stores, dependent: :destroy
  
  validates :name, presence: true
end

app/controllers/admin/store_categories_controller.rb
class Admin::StoreCategoriesController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @store_category = StoreCategory.new
    @store_categories = StoreCategory.all
  end
  
  def edit
    @store_category = StoreCategory.find(params[:id])
  end
  
  def create
    @store_category = StoreCategory.new(store_category_params)
    if @store_category.save
      redirect_to admin_store_categories_path
    else
      render :index
    end
  end
  
  def update
    store_category = StoreCategory.find(params[:id])
    if store_category.update(store_category_params)
      redirect_to admin_store_categories_path
    else
      render :edit
    end
  end
  
  private
  
  def store_category_params
    params.require(:store_category).permit(:name)
  end
end

app/helpers/admin/store_categories_helper.rb
module Admin::StoreCategoriesHelper
end

app/views/admin/store_categories/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <h3>カテゴリー編集</h3>
    </div>
  </div>
  <%= form_with model: @store_category, url: admin_store_category_path, method: :patch do |f| %>
  <div class="row mt-5">
    <div class="col-lg3">
      <h5>カテゴリー名</h5>
    </div>
    <div class="col-lg-3">
      <%= f.text_field :name, class: 'form-control' %>
    </div>
    <div class="col-lg-2">
      <%= f.submit "変更を保存", class: 'btn btn-success btn-block shadow-sm' %>
    </div>
  </div>
  <% end %>
</div>

app/views/admin/store_categories/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <h3>カテゴリー追加・一覧</h3>
    </div>
  </div>
  <div class="row mt-5">
    <div class="col-lg-6">
      <%= form_with model: @store_category, url: admin_store_categories_path do |f| %>
      <div class="row">
        <div class="col-lg-3">
          <h5>カテゴリー名</h5>
        </div>
        <div class="col-lg-5">
          <%= f.text_field :name, class: 'form-control' %>
        </div>
        <div class="col-lg-4">
          <%= f.submit "新規登録", class: 'btn btn-success btn-block shadow-sm' %>
        </div>
      </div>
      <% end %>
    </div>
    <div class="col-lg-5 offset-1">
      <% @store_categories.each do |category| %>
      <div class="row">
        <div class="col-lg-5">
          <h5><%= category.name %></h5>
        </div>
        <div class="col-lg-4">
          <%= link_to "編集する", edit_admin_store_category_path(category.id), class: 'btn btn-light rounded-pill btn-block shadow-sm' %>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-9">
          <hr class="hr1">
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>