config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, skip: [:registrations, :passwords], controllers: {
        sessions: "admin/sessions",
      }
  devise_for :stores, skip: [:passwords], controllers: {
      registrations: "store/registrations",
      sessions: "store/sessions"
    }
  devise_for :customers, skip: [:passwords], controllers: {
      registrations: "public/registrations",
      sessions: "public/sessions"
    }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # guest login
  devise_scope :customer do
    post "customers/guest_sign_in", to: "public/sessions#guest_sign_in"
  end
  # 店舗側
  namespace :store do
    resources :stores do
      resources :items
    end
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
    resources :customers, only: [:index, :show, :edit, :update]
    get "search" => "searches#search"
    resources :item_categories, except: [:new, :show, :destroy]
    get 'item_categories/search'
  end
  # 管理者側
  namespace :admin do
    resources :stores, only: [:index, :show, :create]
    get '/', to: 'admin/home#top'
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:index, :show, :update]
    get "search" => "searches#search"
    resources :store_categories, except: [:new, :show, :destroy]
  end
  # 顧客側
  scope module: :public do
    resources :stores, only: [:index] do
      resources :store_categories, only: [:index, :show]
      resource :favorite, only: [:create, :destroy]
      resources :items, only: [:index, :show] do
        resources :item_categories, only: [:show]
      end
    end
    resources :customers, only: [:update] do
      member do
        get :favorites
      end
    end
      get '/customers/withdraw_confirm' => 'customers#withdraw_confirm', as: "withdraw_confirm"
      patch '/customers/withdraw' => 'customers#withdraw'
      get '/customers/mypage' => 'customers#show', as: "mypage"
      get '/customers/confirmation' => 'customers#confirmation', as: 'confirmation'
      get 'customers/infomation/edit' => 'customers#edit', as: "infomation"
    resources :cart_items, except: [:show, :edit, :new]
      delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
    get 'orders/thanks' => 'orders#thanks'
    post 'orders/confirm' => 'orders#confirm', as: "confirm"
    get 'orders/possible' => 'orders#possible', as: "possible"
    get 'orders/production' => 'orders#production', as: "prodction"
    get 'orders/review' => 'orders#review', as: "review"
    resources :orders, except: [:edit, :update, :destroy]
    root to: 'homes#top'
    get "search" => "searches#search"
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_details, dependent: :destroy
  belongs_to :customer
  has_many :reviews, dependent: :destroy
  
  enum payment_method: { credit_card: 0, cash: 1}
  
  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/logo.PNG')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end
  
  def subtotal
    payment_amount - fee
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @orders = Order.page(params[:page])
  end
  
  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details
  end
end

app/controllers/store/orders_controller.rb
class Store::OrdersController < ApplicationController
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/store/orders_helper.rb
module Store::OrdersHelper
end

app/views/admin/orders/index.html.erb
<div class="container">
  <div class="row">
    <div class="col text-center">
      <h3>注文履歴一覧</h3>
    </div>
  </div>
  <div class="row mt-5">
    <div class="col-lg-3 offset-2">
      <h5>購入日時</h5>
    </div>
    <div class="col-lg-2">
      <h5>購入者</h5>
    </div>
    <div class="col-lg-2">
      <h5>注文個数</h5>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-9 offset-2">
      <div class="border-line">
        <hr class="hr1">
      </div>
    </div>
  </div>
  <% @orders.each do |order| %>
  <div class="row">
    <div class="col-lg-3 offset-2">
      <%= order.created_at.strftime('%Y/%m/%d %H:%M:%S') %>
    </div>
    <div class="col-lg-2">
      <%= order.customer.last_name %><%= order.customer.first_name %>
    </div>
    <div class="col-lg-2">
      <%= order.order_details.sum(:quantity) %>
    </div>
    <div class="col-lg-2">
      <%= link_to "表示する", admin_order_path(order.id), class: 'btn btn-secondary rounded-pill btn-block' %>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-9 offset-2">
      <div class="border-line">
        <hr class="hr1">
      </div>
    </div>
  </div>
  <% end %>
  <div class="row", style="text-align: center;">
    <div class="col-6 offset-5">
      <%= paginate @orders %>
    </div>
  </div>
</div>

app/views/admin/orders/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12 mb-5">
      <h3>注文履歴詳細</h3>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-6">
      <div class="row">
        <div class="col-lg-4">
          <h5>注文日</h5>
        </div>
        <div class="col-lg-4">
          <h5><%= @order.created_at.strftime('%Y/%m/%d') %></h5>
        </div>
      </div>
      <div class="row mt-2">
        <div class="col-lg-4">
          <h5>購入者</h5>
        </div>
        <div class="col-lg-4">
          <h5><%= @order.customer.last_name %><%= @order.customer.first_name %></h5>
        </div>
      </div>
      <div class="row mt-2">
        <div class="col-lg-4">
          <h5>支払方法</h5>
        </div>
        <div class="col-lg-4">
          <h5><%= @order.payment_method_i18n %></h5>
        </div>
      </div>
      <div class="row mt-2">
        <div class="col-lg-4">
          <h5>商品合計</h5>
        </div>
        <div class="col-lg-4">
          <h5>¥<%= @order.subtotal %></h5>
        </div>
      </div>
      <div class="row mt-2">
        <div class="col-lg-4">
          <h5>手数料</h5>
        </div>
        <div class="col-lg-4">
          <h5>¥<%= @order.fee %></h5>
        </div>
      </div>
      <div class="row mt-2">
        <div class="col-lg-4">
          <h4>お支払い金額</h4>
        </div>
        <div class="col-lg-4">
          <h4>¥<%= @order.payment_amount %></h4>
        </div>
      </div>
    </div>
    <div class="col-lg-6">
      <div class="row border-bottom border-white">
        <div class="col-lg-3">
          <h6>商品名</h6>
        </div>
        <div class="col-lg-3">
          <h6>単価(税込)</h6>
        </div>
        <div class="col-lg-3">
          <h6>数量</h6>
        </div>
        <div class="col-lg-3">
          <h6>小計</h6>
        </div>
      </div>
      <% @order.order_details.each do |order_detail| %>
      <div class="row mt-3 border-bottom border-white">
        <div class="col-lg-3">
          <h5><%= order_detail.item.name %></h5>
        </div>
        <div class="col-lg-3">
          <h5>¥<%= order_detail.item.with_tax_price %></h5>
        </div>
        <div class="col-lg-3">
          <h5><%= order_detail.quantity %></h5>
        </div>
        <div class="col-lg-3">
          <h5>¥<%= order_detail.item.with_tax_price * order_detail.quantity %></h5>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>